#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
#
Name     : patchelf
Version  : 0.18.0
Release  : 14
URL      : https://github.com/NixOS/patchelf/archive/0.18.0/patchelf-0.18.0.tar.gz
Source0  : https://github.com/NixOS/patchelf/archive/0.18.0/patchelf-0.18.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: patchelf-bin = %{version}-%{release}
Requires: patchelf-data = %{version}-%{release}
Requires: patchelf-license = %{version}-%{release}
Requires: patchelf-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PatchELF is a simple utility for modifying existing ELF executables and
libraries.  In particular, it can do the following:

%package bin
Summary: bin components for the patchelf package.
Group: Binaries
Requires: patchelf-data = %{version}-%{release}
Requires: patchelf-license = %{version}-%{release}

%description bin
bin components for the patchelf package.


%package data
Summary: data components for the patchelf package.
Group: Data

%description data
data components for the patchelf package.


%package doc
Summary: doc components for the patchelf package.
Group: Documentation
Requires: patchelf-man = %{version}-%{release}

%description doc
doc components for the patchelf package.


%package license
Summary: license components for the patchelf package.
Group: Default

%description license
license components for the patchelf package.


%package man
Summary: man components for the patchelf package.
Group: Default

%description man
man components for the patchelf package.


%prep
%setup -q -n patchelf-0.18.0
cd %{_builddir}/patchelf-0.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1682270809
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1682270809
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/patchelf
cp %{_builddir}/patchelf-%{version}/COPYING %{buildroot}/usr/share/package-licenses/patchelf/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/patchelf

%files data
%defattr(-,root,root,-)
/usr/share/zsh/site-functions/_patchelf

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/patchelf/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/patchelf/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/patchelf.1
